### ISSUE TITLE
 Issues encountered when using the "Go To" Navigation panel - Home Page and Change basemaps

### ISSUE THREAD

**Issue by joaoambiente** [giswqs/geemap-apps#1]
The app's [home page](https://share.streamlit.io/giswqs/geemap-apps/app.py?radio=Home) is showing a **ValueError:**
> This app has encountered an error. The original error message is redacted to prevent data leaks. Full error details have been recorded in the logs (if you're on Streamlit Cloud, click on 'Manage app' in the lower right of your app).

The [Change basemaps](https://share.streamlit.io/giswqs/geemap-apps/app.py?radio=Change+basemaps&ee_assets=None&asset_titles=None) option is showing an **AttributeError:** 
> This app has encountered an error. The original error message is redacted to prevent data leaks. Full error details have been recorded in the logs (if you're on Streamlit Cloud, click on 'Manage app' in the lower right of your app).

**Comment by giswqs** [comment]
Thanks for reporting. The bugs have been fixed. Please try again.
